# -*- coding: utf-8 -*-
"""1분 카운터.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hH9-ICM-awh4rGFWgiu0TRIJvSGyavS-
"""

import streamlit as st
import time

# 페이지 설정
st.set_page_config(page_title="1분 타이머", page_icon="⏱️", layout="centered")

st.title("⏱️ 1분 타이머")

# 버튼 클릭 여부 상태 유지
if "start" not in st.session_state:
    st.session_state.start = False

# 타이머 시작 함수
def start_timer():
    st.session_state.start = True

# 버튼
if not st.session_state.start:
    st.button("시작", on_click=start_timer)

# 타이머 실행
if st.session_state.start:
    timer_slot = st.empty()
    for i in range(60):
        timer_slot.markdown(f"## ⏳ {i + 1}초 경과")
        time.sleep(1)
    timer_slot.markdown("## ✅ 1분 경과!")
    st.session_state.start = False  # 타이머 재시작 가능하게

# Footer
st.markdown("---")
st.caption("🛠️ Made with Streamlit")